# Generated by Django 5.1.1 on 2025-05-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infinity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfinityDB',
            new_name='Infinity',
        ),
    ]
