# Generated by Django 5.1.1 on 2025-05-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infinity', '0002_rename_infinitydb_infinity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infinity',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='infinity',
            old_name='lname',
            new_name='lastname',
        ),
    ]
