# Generated by Django 5.1.1 on 2025-05-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinity', '0003_rename_fname_infinity_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infinity',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
